name: PHP CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install MongoDB extension
        run: sudo apt-get install php-mongodb

      - name: Run basic PHP lint
        run: find . -name "*.php" -exec php -l {} \;
